"""V_00_2_change_in_post_model

Revision ID: 17b55276da0f
Revises: a221f4b0e819
Create Date: 2023-10-06 11:39:44.300943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17b55276da0f'
down_revision: Union[str, None] = 'a221f4b0e819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('number_of_likes', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('number_of_comments', sa.Integer(), nullable=True))
    op.drop_column('posts', 'number_of_like')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('number_of_like', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('posts', 'number_of_comments')
    op.drop_column('posts', 'number_of_likes')
    # ### end Alembic commands ###
