"""V_00_7_remove id from like table

Revision ID: 26494d98a4ca
Revises: 4977043adb3e
Create Date: 2023-10-09 16:27:07.516513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "26494d98a4ca"
down_revision: Union[str, None] = "4977043adb3e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_likes_id", table_name="likes")
    op.drop_column("likes", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "likes", sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.create_index("ix_likes_id", "likes", ["id"], unique=False)
    # ### end Alembic commands ###
