"""V_00_12_add_request_field_in_follower_table

Revision ID: b648512b1b1a
Revises: ef2167a19fda
Create Date: 2023-10-13 23:07:02.521827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b648512b1b1a"
down_revision: Union[str, None] = "ef2167a19fda"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("followers", sa.Column("request", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("followers", "request")
    # ### end Alembic commands ###
