"""V_00_11_add_two_column_in_user_table

Revision ID: ef2167a19fda
Revises: c497401d69ed
Create Date: 2023-10-13 22:10:43.713322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ef2167a19fda"
down_revision: Union[str, None] = "c497401d69ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("no_of_follower", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("no_of_following", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "no_of_following")
    op.drop_column("users", "no_of_follower")
    # ### end Alembic commands ###
