"""V_00_9_add follower table

Revision ID: fa2d37047a18
Revises: 4d1364c11f8d
Create Date: 2023-10-12 18:48:04.166056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fa2d37047a18"
down_revision: Union[str, None] = "4d1364c11f8d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "followers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("follow_by_id", sa.Integer(), nullable=True),
        sa.Column("follow_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["follow_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["follow_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_followers_id"), "followers", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_followers_id"), table_name="followers")
    op.drop_table("followers")
    # ### end Alembic commands ###
